version: '3'

services:
  cassandra1:
    image: cassandra:latest
    container_name: cassandra1
    environment:
      - CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra3
      - CASSANDRA_CLUSTER_NAME=mycluster
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack1
    ports:
      - "9042:9042"
  cassandra2:
    image: cassandra:latest
    container_name: cassandra2
    environment:
      - CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra3
      - CASSANDRA_CLUSTER_NAME=mycluster
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack1
  cassandra3:
    image: cassandra:latest
    container_name: cassandra3
    environment:
      - CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra3
      - CASSANDRA_CLUSTER_NAME=mycluster
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack1
  web:
    build: .
    container_name: flask-web
    ports:
      - "5000:5000"
    depends_on:
      - cassandra1
      - cassandra2
      - cassandra3
    command: ["bash", "-c", "sleep 120 && python ./flask/app.py"]